<div class="container">
    <?php

    // module/Blog/view/album/album/add.phtml:

    $title = 'Add new post';
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    $form->setAttribute('action', $this->url('sampleblog', array('action' => 'add')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('title'));
    echo $this->formRow($form->get('text'));
    echo $this->formSubmit($form->get('submit'));
    //echo $this->formCollection($form);
    echo $this->form()->closeTag();

    ?>
</div>