<?php
$title = 'Delete post';
$this->headTitle($title);
?>
<div class="container">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>Are you sure that you want to delete
        '<?php echo $this->escapeHtml($post->getTitle()); ?>' by
        '<?php echo $this->escapeHtml($post->getText()); ?>'?
    </p>
    <?php
    $url = $this->url('sampleblog', array(
        'action' => 'delete',
        'id' => $this->id,
    ));
    ?>
    <form action="<?php echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo (int)$post->getId(); ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>

</div>