<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SampleBlog\Module'                            => __DIR__ . '/Module.php',
    'SampleBlog\Form\PostForm'                     => __DIR__ . '/src/SampleBlog/Form/PostForm.php',
    'SampleBlog\Mapper\ZendDbSqliteMapper'         => __DIR__ . '/src/SampleBlog/Mapper/ZendDbSqliteMapper.php',
    'SampleBlog\Mapper\PostMapperInterface'        => __DIR__ . '/src/SampleBlog/Mapper/PostMapperInterface.php',
    'SampleBlog\Mapper\ZendDbSqlMapper'            => __DIR__ . '/src/SampleBlog/Mapper/ZendDbSqlMapper.php',
    'SampleBlog\Controller\ListController'         => __DIR__ . '/src/SampleBlog/Controller/ListController.php',
    'SampleBlog\Model\Post'                        => __DIR__ . '/src/SampleBlog/Model/Post.php',
    'SampleBlog\Model\PostInterface'               => __DIR__ . '/src/SampleBlog/Model/PostInterface.php',
    'SampleBlog\Service\PostService'               => __DIR__ . '/src/SampleBlog/Service/PostService.php',
    'SampleBlog\Service\PostServiceInterface'      => __DIR__ . '/src/SampleBlog/Service/PostServiceInterface.php',
    'SampleBlog\Factory\ListControllerFactory'     => __DIR__ . '/src/SampleBlog/Factory/ListControllerFactory.php',
    'SampleBlog\Factory\ZendDbSqlMapperFactory'    => __DIR__ . '/src/SampleBlog/Factory/ZendDbSqlMapperFactory.php',
    'SampleBlog\Factory\PostServiceFactory'        => __DIR__ . '/src/SampleBlog/Factory/PostServiceFactory.php',
    'SampleBlog\Factory\ZendDbSqliteMapperFactory' => __DIR__ . '/src/SampleBlog/Factory/ZendDbSqliteMapperFactory.php',
);
