<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'sample-blog/list/delete'    => __DIR__ . '/view/sample-blog/list/delete.phtml',
    'sample-blog/list/add'       => __DIR__ . '/view/sample-blog/list/add.phtml',
    'sample-blog/list/paginator' => __DIR__ . '/view/sample-blog/list/paginator.phtml',
    'sample-blog/list/index'     => __DIR__ . '/view/sample-blog/list/index.phtml',
    'sample-blog/list/edit'      => __DIR__ . '/view/sample-blog/list/edit.phtml',
);
